import type { SupabaseClient, User } from '@supabase/supabase-js';
import type { Database } from '@/lib/db-types';
import type { FilmEventType } from '@/types/locker-room';
import { configuredAdminEmails, sendEmail } from '@/lib/email';
import { formatBytes } from '@/lib/format';
import { getSiteUrl } from '@/lib/env';

function eventVerb(eventType: FilmEventType) {
  switch (eventType) {
    case 'upload':
      return 'uploaded';
    case 'download':
      return 'downloaded';
    case 'view':
      return 'viewed';
    case 'recording':
      return 'recorded';
    default:
      return 'updated';
  }
}

export async function notifyFilmEvent(
  supabase: SupabaseClient<Database>,
  input: {
    filmId: string;
    eventType: FilmEventType;
    actor: User | null;
  }
) {
  const { data: film, error: filmError } = await supabase
    .from('game_films')
    .select('*, teams(name)')
    .eq('id', input.filmId)
    .maybeSingle();

  if (filmError) throw filmError;
  if (!film) return { skipped: true, reason: 'Film not found.' };

  const { data: recipients, error: recipientError } = await supabase
    .from('notification_recipients')
    .select('email, events, enabled')
    .eq('team_id', film.team_id)
    .eq('enabled', true);

  if (recipientError) throw recipientError;

  const configuredRecipients = (recipients ?? [])
    .filter((recipient) => recipient.events.includes(input.eventType))
    .map((recipient) => recipient.email);

  const to = Array.from(new Set([...configuredRecipients, ...configuredAdminEmails()]));
  if (to.length === 0) return { skipped: true, reason: 'No recipients configured.' };

  const siteUrl = getSiteUrl();
  const actorLabel = input.actor?.email ?? 'An authenticated user';
  const teamName = (film as unknown as { teams?: { name?: string } }).teams?.name ?? 'Raising The Bar Officiating';
  const verb = eventVerb(input.eventType);
  const subject = `The Locker Room: ${film.title} was ${verb}`;
  const detailRows = [
    ['Film', film.title],
    ['Team', teamName],
    ['Event', input.eventType],
    ['User', actorLabel],
    ['Opponent', film.opponent ?? 'Not set'],
    ['Game date', film.game_date ?? 'Not set'],
    ['File', film.original_filename],
    ['Size', formatBytes(film.size_bytes)],
    ['Open app', siteUrl]
  ];

  const htmlRows = detailRows
    .map(([label, value]) => `<tr><td style="padding:8px 12px;color:#777;border-bottom:1px solid #eee">${label}</td><td style="padding:8px 12px;border-bottom:1px solid #eee"><strong>${value}</strong></td></tr>`)
    .join('');

  const html = `
    <div style="font-family:Arial,sans-serif;max-width:680px;margin:auto;color:#151515">
      <h1 style="color:#b8331c">The Locker Room</h1>
      <p>${actorLabel} ${verb} a game film.</p>
      <table style="width:100%;border-collapse:collapse;background:#fff">${htmlRows}</table>
      <p style="color:#777;font-size:12px;margin-top:24px">This notification was generated by The Locker Room for Raising The Bar Officiating.</p>
    </div>`;

  const text = detailRows.map(([label, value]) => `${label}: ${value}`).join('\n');
  return sendEmail({ to, subject, html, text });
}
